version:"3.9"

serveses: 
    valunemongodb:
    image: mongo
    container_name:mongodb
    restart: always
    port:
      - "27017:27017"
    volume:
     - mongo-data:/data/db

  backend:
   build:
     context:./backend
     dockerfile:dockerfile
    container_name: backend
    restart: always
    port:
     - "5000:5000"
    envoiroment:
     PORT: 5000
     MONGO_URI: 
    depends_on:
      - mongodb 
    volume:
    - ./backend:./app
    - /app/node_modules
     

         